services:
  db-beneficiarios:
    image: postgres:16
    container_name: beneficiarios
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password
      POSTGRES_DB: beneficiariosdb
    ports:
      - "5432:5432"